name: Update Json Database
on:
  workflow_dispatch:

jobs:
  scrap_and_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Tools
        run: |
          python -m pip install build wheel
          pip install youtube_archivist==0.0.3
      - name: Run webscrap script
        run: |
          python scripts/update_jsondb.py
      - name: Commit to dev
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update cached json database
          branch: dev
